version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    container_name: bse25-6

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    container_name: group-bse25-6
